# Program: HappinessAnalysis.Rmd
# Author: Joseph (Mac) Abruzzo
# Output: html_document
-------------------------------------------

# R packages
```{r packages}
library("CTT"); library (ellipse) ; library (visreg); library (psych);library ('car') ; library (DMwR) ;library('lavaan') ; library (dplyr)
```

# Reads in the data file
```{r load file}
setwd("C:/Users/Amit/Dropbox/Research/General Emotion/Happiness - value and expectation/Study1")

d <- read.csv("Value_happiness_1.csv",skip =0,na.strings=c("NA","NaN", " "))

d = subset (d, screen ==1)

d$gender = factor (d$gender , label = c("males", "females"))


mytable = table(d$gender) # A will be rows, B will be columns 
mytable # print table 


mean (d$age)
sd(d$age)

str (d$race_w)
```

# Reverses all items that need to be reverse-scored
```{r reverse items}
# Reverse all needed "EXPECT" variables
revExpect3 = recode(d$expect3,"6=1;5=2;4=3;3=4;2=5;1=6")   
revExpect4 = recode(d$expect4,"6=1;5=2;4=3;3=4;2=5;1=6")   

# Reverse all needed "RYFF" variables

revRyff1 = recode(d$ryff1,"6=1;5=2;4=3;3=4;2=5;1=6")
revRyff4 = recode(d$ryff4,"6=1;5=2;4=3;3=4;2=5;1=6")
revRyff5 = recode(d$ryff5,"6=1;5=2;4=3;3=4;2=5;1=6")
revRyff6 = recode(d$ryff6,"6=1;5=2;4=3;3=4;2=5;1=6")
revRyff8 = recode(d$ryff8,"6=1;5=2;4=3;3=4;2=5;1=6")
revRyff13 = recode(d$ryff13,"6=1;5=2;4=3;3=4;2=5;1=6")
revRyff18 = recode(d$ryff18,"6=1;5=2;4=3;3=4;2=5;1=6")



##
```

# Creates all appropriate scales
```{r}

# Scale for expectation of happiness
expect <- as.data.frame(cbind(d$expect1, d$expect2, revExpect3, revExpect4, d$expect5, d$expect6, d$expect7, d$expect8))

head( reliability(expect, itema = TRUE)) # No need to remove any "EXPECT" 
#variables

d$expectScale = rowMeans(expect)

# Scale for psychological well-being
ryff <- as.data.frame(cbind(revRyff1, d$ryff2, d$ryff3, revRyff4, revRyff5, revRyff6,
                            d$ryff7, revRyff8, d$ryff9, d$ryff10, d$ryff11,
                            d$ryff12, revRyff13, d$ryff14, d$ryff15, d$ryff16,
                            d$ryff17, revRyff18))

#head(reliability(ryff, itema = TRUE)) # No need to remove any "RYFF" variables

d$ryffScale <- rowMeans(ryff, na.rm = T)


# Scale for satisfaction with life
swl <- as.data.frame(cbind(d$swl1, d$swl2, d$swl3, d$swl4, d$swl5))

#head(reliability(swl, itema = TRUE)) # No need to remove any "SWL" variables

d$swlScale = rowMeans(swl ,na.rm = T)


# value happienss

value <- as.data.frame(cbind(d$value1, d$value2, d$value3, d$value4, d$value5, d$value6, d$value7))

#head(reliability(value, itema = T))

d$valueScale =rowMeans(value)


#avoid happiness 
avoidunhap = as.data.frame(cbind (d$avoidunhap1,d$avoidunhap2,d$avoidunhap3,d$avoidunhap4,d$avoidunhap5,d$avoidunhap6,d$avoidunhap7))

#head(reliability (avoidunhap, itema =T))

d$avoidunhapScale =rowMeans(avoidunhap)


# bdi 

bdi = as.data.frame (cbind(d$bdi1,d$bdi2,d$bdi3,d$bdi4,d$bdi5,d$bdi6,d$bdi7,d$bdi8,d$bdi9,d$bdi10,d$bdi11,d$bdi12))


d$bdiScale = rowSums(bdi,na.rm = T)

head (d$bdi1)

#Value unhappiness

valueunhap <- as.data.frame(cbind(d$valueunhap1, d$valueunhap2, d$valueunhap3, d$valueunhap4, d$valueunhap5, d$valueunhap6, d$valueunhap7))

#head(reliability(valueunhap, itema = T))

d$valueunhapScale =rowMeans(valueunhap)

# CES

ces = as.data.frame(cbind(d$ces1, d$ces2, d$ces3, d$ces4, d$ces5))

#head(reliability(ces, itema = T))

d$cesScale =rowMeans(ces)


#fear of happiness 

fearhap = as.data.frame(cbind(d$fearhap1, d$fearhap2, d$fearhap3, d$fearhap4, d$fearhap5))

#head(reliability (fearhap, itema =T ))

d$fearhapScale = rowMeans (fearhap)


```


```{r outliers}

# remove outliers

cor_table = data.frame (d$expectScale, d$valueScale, d$valueunhapScale, d$avoidunhapScale,d$fearhapScale, d$swlScale, d$ryffScale, d$bdiScale, d$cesScale)


outlier.scores <- lofactor(cor_table, k=5)
plot(density(outlier.scores))
# pick top 5 as outliers
outliers <- order(outlier.scores, decreasing=T)[1:5]
# who are outliers
print(outliers)

n= nrow(cor_table)
labels = 1:n
labels [-outliers] = "."
biplot(prcomp(cor_table), cex =.8,xlabs = labels)

# print the values and see who they are 
print (d$id[247])

```




**correlation table**
```{r correlation table}


colnames(cor_table) <- c("expect", "value", "value_unhap", "avoid_unhap", "fear_hap", "swl", "ryff", "bdi" , "ces"  )

cor_table1 = cor(cor_table)
cor_table_round = round(cor_table1, digits = 2)


# various ways to plot cor tables 
#plotcorr(cor_table1)

#colorfun <- colorRamp(c("#CC0000","white","#3366CC"), space="Lab")
#plotcorr(cor_table1, col=rgb(colorfun((cor_table1+1)/2), maxColorValue=255))

```


**expectation vs value**
```{r expect vs. value}




r2 = lm (expectScale ~ valueScale, d) ; summary(r2)

r2 = lm (scale(expectScale) ~ scale(valueScale)*gender, d) ; summary(r2)

r2 = lm (expectScale ~ gender, d) ; summary(r2)

r2 = lm (valueScale ~ gender, d) ; summary(r2)

r2 = lm (ryffScale ~ gender, d) ; summary(r2)
r2 = lm (swlScale ~ gender, d) ; summary(r2)
r2 = lm (bdiScale ~ gender, d) ; summary(r2)
r2 = lm (cesScale ~ gender, d) ; summary(r2)



r2 = lm (valueScale ~ gender, d) ; summary(r2)
r2 = lm (ryffScale ~ valueScale *gender, d) ; summary(r2)

r2 = lm (ryffScale ~ expectScale +gender, d) ; summary(r2)
r2 = lm (ryffScale ~ valueScale *gender, d) ; summary(r2)



# examine the supression 

r2 = lm (valueScale ~ expectScale , d) ; summary(r2)


g = (ggplot(d,aes(x=expectScale, y=valueScale ,colour = gender))
  +geom_point(shape=1, position=position_jitter(width=.2,height=.2)) 
  +stat_smooth(method='lm',fill = NA, se = F)
  +labs(title = "interaction between expect and gender", x = "expect scale"))
g;

d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(valueScale ~ expectScale, data = .))))


d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(ryffScale ~ expectScale, data = .))))

d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(ryffScale ~ valueScale, data = .))))


d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(valueScale ~ ryffScale +expectScale, data = .))))

d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(expectScale ~ ryffScale +valueScale, data = .))))


d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(valueScale ~ expectScale, data = .))))

d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(ryffScale ~ expectScale, data = .))))


d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(valueScale ~ ryffScale, data = .))))


g = (ggplot(d,aes(x=expectScale, y=valueScale ,colour = gender))
  +geom_point(shape=1, position=position_jitter(width=.2,height=.2)) 
  +stat_smooth(method='lm',fill = NA, se = F)
  +labs(title = "interaction between expect and gender", x = "expect scale"))
g;

g = (ggplot(d,aes(x=expectScale, y=ryffScale ,colour = gender))
  +geom_point(shape=1, position=position_jitter(width=.2,height=.2)) 
  +stat_smooth(method='lm',fill = NA, se = F)
  +labs(title = "interaction between expect and gender predicting RYFF", x = "expect scale"))
g;

g = (ggplot(d,aes(x=valueScale, y=ryffScale ,colour = gender))
  +geom_point(shape=1, position=position_jitter(width=.2,height=.2)) 
  +stat_smooth(method='lm',fill = NA, se = F)
  +labs(title = "interaction between expect and gender predicting RYFF", x = "expect scale"))
g;


d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(ryffScale ~ expectScale*valueScale, data = .))))



## first lets examine the supression effect 

r2 = lm (expectScale ~ valueScale+ryffScale, d) ; summary(r2)
r2 = lm (expectScale ~ valueScale+swlScale, d) ; summary(r2)
r2 = lm (expectScale ~ valueScale+bdiScale, d) ; summary(r2)
r2 = lm (expectScale ~ valueScale+cesScale, d) ; summary(r2)


d %>%
  group_by(gender) %>% 
  do(r = print(summary(lm(expectScale ~ valueScale, data = .))))


#partial correlation 

a<-with(d,cor.test(expectScale,valueScale))
print(a)

b<-with(d,cor.test(ryffScale,valueScale))
print(b)

c<- with(d, cor.test(expectScale,ryffScale))
print(c)

#FOrmula for partial correlation:
xy<-as.numeric(a$estimate)
xz<-as.numeric(b$estimate)
yz<-as.numeric(c$estimate)
r_xy_z<-(xy - (xz*yz))/(sqrt((1-xz^2)*(1-yz^2)))
print(r_xy_z)
part_cor = (a$estimate - b$estimate*c$estimate)/(sqrt((1-b$estimate^2)*(1-c$estimate^2)))
print(part_cor)
```



```{r value hap}
## first lets examine the supression effect 

r2 = lm (ryffScale ~ expectScale +valueScale +valueunhapScale+avoidunhapScale +fearhapScale, d) ; summary(r2)

r2 = lm (ryffScale ~ expectScale +valueScale +valueunhapScale+avoidunhapScale +fearhapScale, d) ; summary(r2)
# it seems that fear influences the result

r2 = lm (ryffScale ~ valueScale +valueunhapScale , d) ; summary(r2)

r2 = lm (ryffScale ~ valueScale +avoidunhapScale , d) ; summary(r2)
#multi colonearity.


r2 = lm (ryffScale ~ avoidunhapScale +fearhapScale , d) ; summary(r2)

r2 = lm (ryffScale ~ expectScale+valueScale +valueunhapScale , d) ; summary(r2)
# this may indicate a mediation between expect value and value unhap

#examine interactions
r2 = lm (ryffScale ~ valueScale *avoidunhapScale , d) ; summary(r2)

r2 = lm (ryffScale ~ valueScale *fearhapScale , d) ; summary(r2)
# significant

r2 = lm (ryffScale ~ expectScale *avoidunhapScale , d) ; summary(r2)


r2 = lm (ryffScale ~ expectScale *avoidunhapScale , d) ; summary(r2)

r2 = lm (ryffScale ~ expectScale *fearhapScale , d) ; summary(r2)
# significant

r2 = lm (ryffScale ~ valueScale *avoidunhapScale , d) ; summary(r2)


r2 = lm (ryffScale ~ expectScale +valueScale +valueunhapScale+avoidunhapScale +fearhapScale, d) ; summary(r2)

r2 = lm (ryffScale ~  expectScale++valueScale+valueunhapScale+fearhapScale +avoidunhapScale, d) ; summary(r2)


r2 = lm (ryffScale ~  valueunhapScale , d) ; summary(r2)
r2 = lm (ryffScale ~  valueunhapScale +avoidunhapScale, d) ; summary(r2)


r2 = lm(ryffScale ~ fearhapScale + avoidunhapScale, d) ; summary (r2)

r2 = lm (ryffScale ~  valueScale +avoidunhapScale, d) ; summary(r2)

r2 = lm (swlScale ~  valueScale +avoidunhapScale, d) ; summary(r2)
r2 = lm (bdiScale ~  valueScale +avoidunhapScale, d) ; summary(r2)


r2 = lm (cesScale ~  valueScale +avoidunhapScale, d) ; summary(r2)



r2 = lm (ryffScale ~  valueScale+valueunhapScale, d) ; summary(r2)




r2 = lm (expectScale ~  ryffScale+valueScale, d) ; summary(r2)

r2 = lm (valueScale ~  ryffScale+ expectScale, d) ; summary(r2)




```



```{r sem}

model1 = '
  ryff ~ expect +value +value_unhap+ avoid_unhap + fear_hap
  swl ~ expect +value +value_unhap+ avoid_unhap + fear_hap
  ces ~ expect +value +value_unhap+ avoid_unhap + fear_hap
  bdi ~ expect +value +value_unhap+ avoid_unhap + fear_hap



'

fit1 = sem(model1, fixed.x = F, sample.cov = cor_table1, sample.nobs = 250) ;summary(fit1)



```

** race**
```{r race}




d$race_w = factor (d$race_w, label = c("not-White", "White"))

d$race_as = factor (d$race_as, label = c("not-Asian", "Asian"))

d$race= factor (d$race, label = c("White", "Asian", "White & Asian", "Other"))


r= lm(expectScale ~ valueScale * race_w , d) ; summary (r)

r= lm(expectScale ~ valueScale * race_as , d) ; summary (r)

g = (ggplot(d,aes(x=valueScale, y=expect ,colour = race_w))
  +geom_point(shape=1, position=position_jitter(width=.2,height=.2)) 
  +stat_smooth(method='lm',fill = NA, se = F)
  +labs(title = "interaction between expect and gender predicting RYFF", x = "expect scale"))
g;

d %>%
  group_by(race_w) %>% 
  do(r = print(summary(lm(expectScale ~ valueScale, data = .))))

d %>%
  group_by(race_as) %>% 
  do(r = print(summary(lm(expectScale ~ valueScale, data = .))))

d %>%
  group_by(race) %>% 
  do(r = print(summary(lm(expectScale ~ valueScale, data = .))))

str(d$race)

race_m = d %>%
    group_by(race) %>%
    summarise(
    expect_m =mean(expectScale, na.rm = T), 
    value_m = mean(valueScale, na.rm = T),
    rayff_m = mean(ryffScale),
    bdi_m = mean (bdiScale)
    )

r = lm(expectScale ~ valueScale * race , d) ; summary (r)

```



```{r}
r = lm(expectScale ~ valueScale + edufather , d) ; summary (r)
r = lm(expectScale ~ valueScale + edumother , d) ; summary (r)


r = lm(expectScale ~  edumother , d) ; summary (r)
r = lm(valueScale ~ edumother , d) ; summary (r)


r = lm(expectScale ~  edufather , d) ; summary (r)
r = lm(valueScale ~ edufather , d) ; summary (r)

```

